// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChI7SwNRyk80YofbGVIwZZoZuTYUy9AEE',
    appId: '1:554738307135:android:18562342b016e7e214688a',
    messagingSenderId: '554738307135',
    projectId: 'test-a5631',
    databaseURL: 'https://test-a5631-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-a5631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8IIh-A_Umq94HeMwQR9nzgiakwS_CmaU',
    appId: '1:554738307135:ios:ff2c9f4a7f70da6914688a',
    messagingSenderId: '554738307135',
    projectId: 'test-a5631',
    databaseURL: 'https://test-a5631-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-a5631.firebasestorage.app',
    iosBundleId: 'com.sanslab.iotchannuoi.iotChanNuoiApp',
  );

}