// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPa_9UtVGITQmsXs85_vjhqdKAck2eUQ',
    appId: '1:649257186668:android:f785285171c65701a32f49',
    messagingSenderId: '649257186668',
    projectId: 'embedded-34716',
    databaseURL: 'https://embedded-34716-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'embedded-34716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWPsxXd7Z37QPL0ekBKEQRzRUNxbtsK0A',
    appId: '1:649257186668:ios:d894cb74da96e7ada32f49',
    messagingSenderId: '649257186668',
    projectId: 'embedded-34716',
    databaseURL: 'https://embedded-34716-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'embedded-34716.firebasestorage.app',
    iosBundleId: 'com.sanslab.iotchannuoi.iotChanNuoiApp',
  );
}
